# project definitions
project: java_guide
audience: programmers
product: mydoc
platform: all
version: all
output: web
destination: ../doc_outputs/mydoc/programmers
topnav_title: Arend Peter's Java Guide
homepage_title: Introduction
site_title: Java Guide
project_folder: mydoc
company_name:
footer_image_location:
github_editme_path: tomjohnson1492/documentation-theme-jekyll/edit/reviews
disqus_shortname:
# variables


sidebar_tagline: JavaGuide
sidebar_version:
theme_file: theme-red.css
pdf_file_name: java_guide_pdf.pdf

# the algolia entries here are experimental only.

#gems:
#  - algoliasearch-jekyll
#algolia:
#  application_id: 'HXUBJERYYB'
#  index_name:     'documentation_theme_jekyll_programmers'
port: 4009

exclude:
  - _site
  - _drafts
  - configs/
  - doc/mydoc_writers*

# same for all
host: 127.0.0.1
feedback_email: apc@arendpeter.com

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true

collections:
  tooltips:
    output: false

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      comments: true
      search: true
      tooltip: true
